version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vp-ops"
s3_bucket = "cf-templates-deniz"
s3_prefix = "vp-ops"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
